[tool.poetry]
name = "vapor"
version = "0.1.0"
description = "Execute VCF tools in parallel."
authors = ["Christopher Schröder"]

[tool.poetry.scripts]
vapor = "vapor:main"

[tool.poetry.dependencies]
python = "^3.7"
pysam = "^0.16"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^1.10"
black = { version = "^19.10b0", python = "^3.7" }

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
